name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root

outputs:
  status:
    description: Validate status
    value: ${{ steps.parse-result.outputs.status }}
  detail:
    description: Validate detail
    value: ${{ steps.parse-result.outputs.detail }}

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.3.0

    - name: Validate template
      id: validate-template
      run: |
        result=$(deno run --allow-read ${{ github.action_path }}/src/main.ts ${{ inputs.path }})
        echo "::set-output name=result::$result"
      shell: bash

    - name: Parse Result
      id: parse-result
      run: |
        echo "::set-output name=status::${{ fromJSON(steps.validate-template.outputs.result).status }}"
        echo "::set-output name=detail::${{ fromJSON(steps.validate-template.outputs.result).detail }}"
      shell: bash