name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.3.0

    - name: Validate template
      id: validate-template
      run: |
        result=$(deno run --allow-read ${{ github.action_path }}/src/main.ts ${{ inputs.path }})
        echo ::set-output name=result::$result
      shell: bash

    - name: Parse Result
      run: |
        status=${{ fromJSON(steps.validate-template.outputs.result).status }}
        detail=${{ fromJSON(steps.validate-template.outputs.result).detail }}
        echo ::set-output name=status::$status
        echo ::set-output name=detail::$detail
      shell: bash

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.validate-template.outputs.detail }}