name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root

outputs:
  status:
    description: Validate status
    value: ${{ fromJSON(steps.validate-template.outputs.result).status }}
  detail:
    description: Validate detail
    value: ${{ fromJSON(steps.validate-template.outputs.result).detail }}

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.3.0

    - name: Git pull
      run: git pull
      shell: bash

    - name: Git diff
      id: git-diff
      run: |
        changes="$(git diff origin/main --name-only ./templates)"
        echo echo "::set-output name=changes::$changes"
      shell: bash

    - name: Validate template
      id: validate-template
      run: echo "::set-output name=result::$(deno run --allow-read ${{ github.action_path }}/src/main.ts ${{ steps.git-diff.outputs.changes }})"
      shell: bash