name: Validate template

description: Validate ADF template

inputs:
  path:
    required: true
    description: Project root

outputs:
  status:
    description: Validate status
    value: ${{ fromJSON(steps.validate-template.outputs.result).status }}
  detail:
    description: Validate detail
    value: ${{ fromJSON(steps.validate-template.outputs.result).detail }}

runs:
  using: composite
  steps:
    - name: Setup Deno environment
      uses: denolib/setup-deno@v2.3.0

    - name: Update remote
      run: git remote update origin --prune
      shell: bash

    - name: Diff
      id: diff
      run: git diff origin/main --only-name templates
      shell: bash

    - name: Validate template
      id: validate-template
      run: echo "::set-output name=result::$(deno run --allow-read ${{ github.action_path }}/src/main.ts abc)"
      shell: bash